[network]
enabled = true
listen_address = "0.0.0.0"
listen_port = 8333
max_peers = 10
connection_timeout_secs = 10
bootstrap_nodes = ["/ip4/127.0.0.1/tcp/8333"]
enable_upnp = false
enable_mdns = true
peer_discovery_interval_secs = 60
max_message_size = 10485760
ban_duration_secs = 300
rate_limit_per_peer = 1000

[mining]
enabled = true
wallet_path = "miner-wallet.json"
target_block_time_secs = 10
difficulty_adjustment_interval = 20
stratum_bind_address = "0.0.0.0"
stratum_bind_port = 3333
local_mining_enabled = true
cpu_threads = 2

[rpc]
enabled = true
bind_address = "127.0.0.1"
port = 8082
max_connections = 100
request_timeout_secs = 30
max_request_size = 1048576
enable_cors = true
allowed_origins = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3000",
]
rate_limit_requests_per_minute = 1000
rate_limit_burst_size = 100
enable_authentication = false
admin_endpoints_enabled = true

[security]
jwt_secret = "4778114abc384c234d87c7308c4986b175d7a1516ca50c15527e893a4a269a0c"
jwt_expiry_hours = 1
admin_api_key = "6fd3a3294751b8280bae09ad17802226d67b030f6b2295c5d784f04747b72450"
enable_rate_limiting = true
enable_ip_blocking = true
max_failed_attempts = 10
block_duration_minutes = 1
enable_request_signing = false
require_https = false
enable_firewall = false
trusted_proxies = []

[storage]
data_directory = "./dev-data"
backup_directory = "./dev-backups"
max_database_size_mb = 1024
cache_size_mb = 128
enable_compression = false
enable_encryption = false
auto_backup = false
backup_interval_hours = 24
retention_days = 30
sync_mode = "Fast"

[consensus]
difficulty_adjustment_interval = 20
max_block_size = 524288
max_transactions_per_block = 100
min_transaction_fee = 1
max_reorg_depth = 10
checkpoint_interval = 50
finality_depth = 100
genesis_supply = 8888
mining_reward_halving_interval = 111000
initial_mining_reward = 8888

[consensus.target_block_time]
secs = 10
nanos = 0

[consensus.argon2_config]
memory_cost = 4096
time_cost = 1
parallelism = 1
output_length = 32
salt_length = 16
