[network]
enabled = true
listen_address = "0.0.0.0"
listen_port = 8333
max_peers = 10
connection_timeout_secs = 15
bootstrap_nodes = []
enable_upnp = false
enable_mdns = true
peer_discovery_interval_secs = 120
max_message_size = 1048576
ban_duration_secs = 600
rate_limit_per_peer = 500

[mining]
enabled = true
thread_count = 1
nonce_chunk_size = 1000
stats_update_interval_secs = 10
enable_cpu_affinity = false
thermal_throttle_temp = 70.0
power_limit_watts = 0.0
target_block_time_secs = 15
difficulty_adjustment_interval = 30

[mining.argon2_config]
memory_cost = 2048
time_cost = 1
parallelism = 1
output_length = 32
salt_length = 16

[rpc]
enabled = true
bind_address = "127.0.0.1"
port = 8080
max_connections = 50
request_timeout_secs = 30
max_request_size = 1048576
enable_cors = true
allowed_origins = ["http://localhost:3000"]
rate_limit_requests_per_minute = 100
rate_limit_burst_size = 10
enable_authentication = false
admin_endpoints_enabled = true

[storage]
data_directory = "./dev-data"
backup_directory = "./backups"
max_database_size_mb = 512
cache_size_mb = 64
enable_compression = true
enable_encryption = false
auto_backup = false
backup_interval_hours = 24
retention_days = 7
sync_mode = "Fast"

[consensus]
difficulty_adjustment_interval = 30
max_block_size = 524288
max_transactions_per_block = 100
min_transaction_fee = 500
max_reorg_depth = 10
checkpoint_interval = 50
finality_depth = 100
genesis_supply = 1000000000000000
mining_reward_halving_interval = 100000
initial_mining_reward = 100000000000
