[network]
enabled = true
listen_address = "0.0.0.0"
listen_port = 8333
max_peers = 100
connection_timeout_secs = 10
bootstrap_nodes = [
    "/ip4/127.0.0.1/tcp/8334"
]
enable_upnp = false
enable_mdns = true
peer_discovery_interval_secs = 30
max_message_size = 10485760
ban_duration_secs = 300
rate_limit_per_peer = 1000

[mining]
enabled = true
wallet_path = "./miner-wallet.json"
thread_count = 8
nonce_chunk_size = 5000
stats_update_interval_secs = 5
enable_cpu_affinity = false
thermal_throttle_temp = 70.0
power_limit_watts = 50.0
target_block_time_secs = 1
difficulty_adjustment_interval = 600

[mining.argon2_config]
memory_cost = 65536
time_cost = 1
parallelism = 4
output_length = 32
salt_length = 16

[rpc]
enabled = true
bind_address = "0.0.0.0"
port = 8082
max_connections = 100
request_timeout_secs = 30
max_request_size = 1048576
enable_cors = true
allowed_origins = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3000",
    "*"
]
rate_limit_requests_per_minute = 1000
rate_limit_burst_size = 100
enable_authentication = false
admin_endpoints_enabled = true

[security]
jwt_secret = "GiGC7FId5m1s75iIRYmWny1OKSmST8J2"
jwt_expiry_hours = 1
admin_api_key = "OJK7DSybNYDaraV9UmQQxScEecVbhKt4"
enable_rate_limiting = true
enable_ip_blocking = true
max_failed_attempts = 10
block_duration_minutes = 1
enable_request_signing = false
require_https = false
enable_firewall = false
trusted_proxies = []

[storage]
data_directory = "./core-data"
backup_directory = "./dev-backups"
max_database_size_mb = 1024
cache_size_mb = 128
enable_compression = false
enable_encryption = false
auto_backup = false
backup_interval_hours = 24
retention_days = 30
sync_mode = "Fast"

[consensus]
difficulty_adjustment_interval = 600
max_block_size = 524288
max_transactions_per_block = 100
min_transaction_fee = 1
max_reorg_depth = 10
checkpoint_interval = 20
finality_depth = 50
genesis_supply = 1000
mining_reward_halving_interval = 1000000
initial_mining_reward = 1000

# Transaction fee structure (aligned with transaction.rs constants)
# - Base fee: 1 NANO per transaction
# - Size fee: 1 NANO per byte  
# - Min fee: 1 NANO total
# - Max fee: 100000 NANO (1000 NUMI)

[consensus.target_block_time]
secs = 1
nanos = 500000000
